services:

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "8080:8080"


  postgres:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    


volumes:
  postgres_data: {}





